#pragma once

/**
 * @brief Supported types order outcomes that can arise when processing an order in the exchanges system.
 * 
 */
enum OrderOutcomeType {
    NOT_PROCESSED,
    SUCCESS,
    FAIL,
    INVALID_REQUEST_TYPE,
    INVALID_SYMBOL_OR_SIZE,
    INSUFFICIENT_LIQUIDITY,
    NON_USER_ACCESS_TO_ORDER,
    ORDER_ID_NON_EXISTENT,
    ORDER_ID_ALREADY_PLACED_ERROR,
    ORDER_COMPLETELY_FILLED,
    ORDER_NOT_FILLED,
    ORDER_PARTIALLY_FILLED,
    ORDER_PARTIALLY_FILLED_INSERTION_ERROR,
    ORDER_EXISTS_PRICE_CHANGE_ERROR,
    ORDER_EXISTS_SIZE_CHANGE_ERROR,
    ORDER_EXISTS_CANCEL_ERROR,
    ORDER_CANCEL_SUCCESS
};